### ISSUE TITLE
Typo in config example documentation

### ISSUE THREAD

**Issue by jakehamtexas** [axkirillov/easypick.nvim#5]
The picker `branch_diff` is shown being passed a `string`, but it expects a table that looks like `{ base_branch = "develop" }`. The documentation should be updated to show the correct table.

**Comment by axkirillov** [comment]
Hi! This is true, thank you for pointing it out 🙂

**Comment by axkirillov** [comment]
https://github.com/axkirillov/easypick.nvim/commit/bccee73f0e3be97d06cbbe47e36fb51f097dbb67
